# Generated by Django 4.0 on 2021-12-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phase_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('phase_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='professor_db',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('prof_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project_db',
            fields=[
                ('domain', models.CharField(max_length=20, null=True)),
                ('proj_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_db',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('sem', models.PositiveSmallIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('branch', models.CharField(max_length=2, null=True)),
                ('prof_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.professor_db')),
                ('proj_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project_db')),
            ],
        ),
        migrations.CreateModel(
            name='rubrics_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=256)),
                ('rmarks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rnumber', models.IntegerField()),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phase_db')),
            ],
        ),
        migrations.AddField(
            model_name='project_db',
            name='stu_usn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.student_db'),
        ),
        migrations.CreateModel(
            name='evaluation_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phase_db')),
                ('prof_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.professor_db')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student_db')),
            ],
        ),
        migrations.CreateModel(
            name='deliverables_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=256)),
                ('ppt', models.CharField(max_length=256)),
                ('gdrive_link', models.CharField(max_length=256)),
                ('phase_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.phase_db')),
                ('usn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.student_db')),
            ],
        ),
    ]
