# Generated by Django 4.0 on 2021-12-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_db',
            name='proj_name',
        ),
        migrations.AlterField(
            model_name='project_db',
            name='stu_usn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student_db'),
        ),
        migrations.AlterField(
            model_name='student_db',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
