# Generated by Django 4.0 on 2021-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_db_proj_name_alter_project_db_stu_usn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_db',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
